# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTunes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyTunes

    pod 'Alamofire'
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'Kingfisher', '~> 7.0'

  target 'MyTunesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyTunesUITests' do
    # Pods for testing
  end
  
  # New Swift Project pods
  def network_pods
    pod 'Alamofire', :modular_headers => true
  end

target 'STNetwork' do
  
  project 'MyTunes.project'
  
  network_pods
  target :STNetworkTests
end

end
